const A={section:"dashboard",movies:JSON.parse(localStorage.getItem("ps_movies")||"null")||[
{id:1,title:"PRINCE (শাহিব খান)",type:"Movie",year:2026,rating:8.7,clicks:1842,downloads:921,status:"Published"},
{id:2,title:"ROCKSTAR",type:"Movie",year:2026,rating:8.1,clicks:1421,downloads:702,status:"Published"},
{id:3,title:"SPIDER-MAN: Brand New Day",type:"Movie",year:2026,rating:8.5,clicks:1207,downloads:641,status:"Draft"}],
users:12480,points:156240,unlockCost:5,unlockHours:15,adReward:2,dailyAdLimit:20,adultEnabled:true};

const $=s=>document.querySelector(s);
const content=$("#content"), title=$("#pageTitle"), toastEl=$("#toast");
function save(){localStorage.setItem("ps_movies",JSON.stringify(A.movies))}
function toast(t){toastEl.textContent=t;toastEl.classList.add("show");setTimeout(()=>toastEl.classList.remove("show"),1700)}
function money(n){return Number(n).toLocaleString()}
function setSection(s){A.section=s;title.textContent=s==="dashboard"?"Dashboard":s[0].toUpperCase()+s.slice(1);document.querySelectorAll("#sideNav button").forEach(b=>b.classList.toggle("active",b.dataset.section===s));render()}
document.querySelectorAll("#sideNav button").forEach(b=>b.onclick=()=>setSection(b.dataset.section));
$("#mobileMenu").onclick=()=>$(".sidebar").classList.toggle("open");
$("#openUser").onclick=()=>location.href="index.html";
$("#logout").onclick=()=>toast("Demo sign-out complete");

function dashboard(){return `<div class="grid stats">
<div class="card stat"><span class="label">Total Users</span><div class="num">${money(A.users)}</div><span class="up">↑ 8.4% this month</span><span class="ico">♙</span></div>
<div class="card stat"><span class="label">Movies</span><div class="num">${A.movies.length}</div><span class="up">↑ 12 added</span><span class="ico">▣</span></div>
<div class="card stat"><span class="label">Points Issued</span><div class="num">${money(A.points)}</div><span class="up">↑ 14.2% this week</span><span class="ico">◈</span></div>
<div class="card stat"><span class="label">Pending Payments</span><div class="num">3</div><span class="up">Needs review</span><span class="ico">৳</span></div></div>
<div class="grid section-grid">
<div class="card"><h3>Platform activity</h3><div class="muted" style="font-size:10px">Unlocks & ad impressions — last 7 days</div><div class="chart">${[38,55,48,72,66,91,76].map(x=>`<div class="bar" style="height:${x}%"></div>`).join("")}</div></div>
<div class="card"><h3>Quick controls</h3><div class="quick"><button onclick="openMovie()"><b>＋ Add movie</b>Publish new title</button><button onclick="setSection('payments')"><b>৳ Payments</b>Review purchases</button><button onclick="setSection('ads')"><b>◉ Ad settings</b>Rewards & limits</button><button onclick="setSection('points')"><b>◈ Points</b>Unlock pricing</button></div></div></div>
<div class="card" style="margin-top:14px"><h3>System status</h3><div class="switch"><span>Movie service</span><span class="badge green">ONLINE</span></div><div class="switch"><span>Points & unlock</span><span class="badge green">ACTIVE</span></div><div class="switch"><span>Adult section</span><span class="badge ${A.adultEnabled?"green":"red"}">${A.adultEnabled?"ENABLED":"DISABLED"}</span></div></div>`}

function movies(){return `<div class="toolbar"><div class="left"><button class="btn primary" onclick="openMovie()">＋ Add Movie</button><button class="btn" onclick="toast('TMDB import is ready for backend connection')">Import from TMDB</button></div><input class="search" id="movieSearch" placeholder="Search title..." oninput="filterMovies()"></div><div class="card table-wrap"><table class="table"><thead><tr><th>Movie</th><th>Type</th><th>Rating</th><th>Clicks</th><th>Downloads</th><th>Status</th><th>Action</th></tr></thead><tbody id="movieBody">${movieRows(A.movies)}</tbody></table></div>`}
function movieRows(ms){return ms.map(m=>`<tr><td><div class="movie-row"><div class="thumb">${m.title.slice(0,1)}</div><div><b>${m.title}</b><div class="muted">${m.year}</div></div></div></td><td>${m.type}</td><td>⭐ ${m.rating}</td><td>${money(m.clicks)}</td><td>${money(m.downloads)}</td><td><span class="badge ${m.status==="Published"?"green":""}">${m.status}</span></td><td><button class="btn" onclick="editMovie(${m.id})">Edit</button> <button class="btn danger" onclick="deleteMovie(${m.id})">Delete</button></td></tr>`).join("")}
function filterMovies(){const q=$("#movieSearch").value.toLowerCase();$("#movieBody").innerHTML=movieRows(A.movies.filter(m=>m.title.toLowerCase().includes(q)))}

function users(){return `<div class="toolbar"><div class="left"><button class="btn" onclick="toast('User export queued')">Export CSV</button><button class="btn danger" onclick="toast('Bulk action requires backend authorization')">Bulk action</button></div><input class="search" placeholder="Search Telegram user..."></div><div class="card table-wrap"><table class="table"><thead><tr><th>User</th><th>Points</th><th>Unlocks</th><th>Ads today</th><th>Status</th><th>Action</th></tr></thead><tbody>${[["Demo User","1,240",18,7,"Active"],["Movie Lover","530",6,19,"Active"],["New Member","20",0,3,"Active"],["Blocked User","0",0,0,"Blocked"]].map((u,i)=>`<tr><td><div class="movie-row"><div class="avatar">${i+1}</div><div><b>${u[0]}</b><div class="muted">@demo_user_${i+1}</div></div></div></td><td>${u[1]}</td><td>${u[2]}</td><td>${u[3]}/${A.dailyAdLimit}</td><td><span class="badge ${u[4]==="Active"?"green":"red"}">${u[4]}</span></td><td><button class="btn" onclick="toast('User details opened')">Manage</button></td></tr>`).join("")}</tbody></table></div>`}

function points(){return `<div class="grid section-grid"><div class="card"><h3>Unlock economy</h3><div class="form-grid">
<div class="field"><label>Movie unlock cost (points)</label><input id="unlockCost" type="number" value="${A.unlockCost}"></div>
<div class="field"><label>Unlock duration (hours)</label><input id="unlockHours" type="number" value="${A.unlockHours}"></div>
<div class="field"><label>New-user bonus</label><input id="bonus" type="number" value="10"></div>
<div class="field"><label>Referral reward</label><input id="ref" type="number" value="5"></div></div><button class="btn primary" style="margin-top:14px" onclick="savePoints()">Save economy</button></div>
<div class="card"><h3>Rules</h3><div class="switch"><span>Unlimited movie unlocks while unlocked</span><span class="badge green">ON</span></div><div class="switch"><span>Daily ad limit applies only to earning points</span><span class="badge green">ON</span></div><div class="switch"><span>Points expire</span><span class="badge">OFF</span></div></div></div>`}
function savePoints(){A.unlockCost=+$("#unlockCost").value;A.unlockHours=+$("#unlockHours").value;toast("Points & unlock settings saved")}

function ads(){return `<div class="grid section-grid"><div class="card"><h3>Ad reward system</h3><div class="form-grid"><div class="field"><label>Points per completed ad</label><input id="adReward" type="number" value="${A.adReward}"></div><div class="field"><label>Daily earning limit</label><input id="dailyAdLimit" type="number" value="${A.dailyAdLimit}"></div><div class="field"><label>Reward block ID</label><input value="43222"></div><div class="field"><label>Adult ad block ID</label><input placeholder="Add separate adult block ID"></div></div><button class="btn primary" style="margin-top:14px" onclick="saveAds()">Save ad settings</button></div><div class="card"><h3>Ad placement</h3><div class="switch"><span>Home banner</span><span class="toggle on" onclick="this.classList.toggle('on')"><i></i></span></div><div class="switch"><span>Rewarded unlock</span><span class="toggle on" onclick="this.classList.toggle('on')"><i></i></span></div><div class="switch"><span>Adult ads</span><span class="toggle on" onclick="this.classList.toggle('on')"><i></i></span></div></div></div>`}
function saveAds(){A.adReward=+$("#adReward").value;A.dailyAdLimit=+$("#dailyAdLimit").value;toast("Ad reward settings saved")}

function tasks(){return `<div class="toolbar"><button class="btn primary" onclick="openTask()">＋ Add Task</button></div><div class="card table-wrap"><table class="table"><thead><tr><th>Task</th><th>Reward</th><th>Daily limit</th><th>Status</th><th>Action</th></tr></thead><tbody>${[["Watch rewarded ad",A.adReward,A.dailyAdLimit,"Active"],["Join Telegram channel",5,1,"Active"],["Refer a friend",5,10,"Active"],["Daily login",2,1,"Active"]].map(t=>`<tr><td><b>${t[0]}</b></td><td>+${t[1]} pts</td><td>${t[2]}</td><td><span class="badge green">${t[3]}</span></td><td><button class="btn" onclick="openTask('${t[0]}')">Edit</button></td></tr>`).join("")}</tbody></table></div>`}

function payments(){return `<div class="card table-wrap"><table class="table"><thead><tr><th>User</th><th>Package</th><th>Amount</th><th>Payment ID</th><th>Proof</th><th>Status</th><th>Action</th></tr></thead><tbody>${[["Demo User","500 Points","৳100","TXN-92811","Image","Pending"],["Movie Lover","1200 Points","৳200","TXN-92772","Image","Pending"],["Test Buyer","2500 Points","৳400","TXN-92720","Image","Pending"],["Old User","500 Points","৳100","TXN-92111","Image","Approved"]].map(p=>`<tr><td><b>${p[0]}</b></td><td>${p[1]}</td><td>${p[2]}</td><td>${p[3]}</td><td><button class="btn" onclick="toast('Payment proof preview')">View</button></td><td><span class="badge ${p[5]==="Approved"?"green":"red"}">${p[5]}</span></td><td><button class="btn primary" onclick="toast('Payment approved in demo')">Approve</button></td></tr>`).join("")}</tbody></table></div>`}

function adult(){return `<div class="grid section-grid"><div class="card"><h3>Adult library</h3><div class="switch"><span>Enable adult section</span><span class="toggle ${A.adultEnabled?"on":""}" onclick="A.adultEnabled=!A.adultEnabled;render()"><i></i></span></div><div class="switch"><span>Separate adult ad block</span><span class="badge">CONFIGURE</span></div><div class="switch"><span>18+ confirmation</span><span class="badge green">REQUIRED</span></div><button class="btn primary" style="margin-top:15px" onclick="openAdultMovie()">＋ Add adult movie</button></div><div class="card"><h3>Adult content safety</h3><div class="muted" style="font-size:11px;line-height:1.7">Adult content is isolated from the normal movie library. Use a separate ad block and explicit 18+ gate. This demo does not store real payment or private user data.</div></div></div>`}

function requests(){return `<div class="card table-wrap"><table class="table"><thead><tr><th>User</th><th>Requested title</th><th>Date</th><th>Priority</th><th>Status</th><th>Action</th></tr></thead><tbody>${[["@demo_user_1","Avengers: Secret Wars","Today","High","Pending"],["@moviefan","Interstellar","Yesterday","Normal","Pending"],["@sifat_demo","Dune: Part Three","Yesterday","Normal","Searching"]].map(r=>`<tr><td>${r[0]}</td><td><b>${r[1]}</b></td><td>${r[2]}</td><td>${r[3]}</td><td><span class="badge">${r[4]}</span></td><td><button class="btn" onclick="toast('Request marked as handled')">Manage</button></td></tr>`).join("")}</tbody></table></div>`}

function broadcast(){return `<div class="card"><h3>Broadcast center</h3><div class="form-grid"><div class="field"><label>Audience</label><select><option>All users</option><option>Active users</option><option>Users with points</option></select></div><div class="field"><label>Message type</label><select><option>Text</option><option>Movie announcement</option></select></div></div><div class="field" style="margin-top:12px"><label>Message</label><textarea placeholder="Write your broadcast..."></textarea></div><button class="btn primary" style="margin-top:12px" onclick="toast('Broadcast queued in demo')">Send Broadcast</button></div>`}

function settings(){return `<div class="grid section-grid"><div class="card"><h3>App settings</h3><div class="form-grid"><div class="field"><label>App name</label><input value="Prime Scene"></div><div class="field"><label>Default language</label><select><option>English</option><option>বাংলা</option></select></div><div class="field"><label>Bot username</label><input value="@Cinehub4bot"></div><div class="field"><label>Telegram channel</label><input placeholder="@your_channel"></div></div><button class="btn primary" style="margin-top:14px" onclick="toast('App settings saved')">Save settings</button></div><div class="card"><h3>Security</h3><div class="switch"><span>Admin-only panel</span><span class="badge green">ENFORCE</span></div><div class="switch"><span>Maintenance mode</span><span class="toggle" onclick="this.classList.toggle('on')"><i></i></span></div><div class="switch"><span>New registrations</span><span class="toggle on" onclick="this.classList.toggle('on')"><i></i></span></div></div></div>`}

function render(){const views={dashboard,movies,users,points,ads,tasks,payments,adult,requests,broadcast,settings};content.innerHTML=views[A.section]()}
function openMovie(id=null){const m=id?A.movies.find(x=>x.id===id):null;showModal(`<div class="modal-head"><h2>${m?"Edit":"Add"} Movie</h2><button class="btn" onclick="closeModal()">×</button></div><div class="form-grid"><div class="field"><label>Title</label><input id="mTitle" value="${m?.title||""}"></div><div class="field"><label>Year</label><input id="mYear" type="number" value="${m?.year||2026}"></div><div class="field"><label>TMDB ID</label><input id="mTmdb" placeholder="Optional"></div><div class="field"><label>Rating</label><input id="mRating" type="number" step=".1" value="${m?.rating||8}"></div><div class="field"><label>Server 1 URL</label><input id="s1" placeholder="https://..."></div><div class="field"><label>Server 2 URL</label><input id="s2" placeholder="https://..."></div></div><button class="btn primary" style="margin-top:15px" onclick="saveMovie(${id||0})">Save Movie</button>`)}
function editMovie(id){openMovie(id)}
function saveMovie(id){const x={id:id||Date.now(),title:$("#mTitle").value||"Untitled Movie",type:"Movie",year:+$("#mYear").value||2026,rating:+$("#mRating").value||8,clicks:id?(A.movies.find(m=>m.id===id)?.clicks||0):0,downloads:id?(A.movies.find(m=>m.id===id)?.downloads||0):0,status:"Published"};if(id)A.movies=A.movies.map(m=>m.id===id?x:m);else A.movies.unshift(x);save();closeModal();render();toast("Movie saved successfully")}
function deleteMovie(id){if(confirm("Delete this movie?")){A.movies=A.movies.filter(m=>m.id!==id);save();render();toast("Movie deleted")}}
function openTask(name=""){showModal(`<div class="modal-head"><h2>${name?"Edit":"Add"} Task</h2><button class="btn" onclick="closeModal()">×</button></div><div class="field"><label>Task name</label><input id="taskName" value="${name}"></div><div class="form-grid" style="margin-top:12px"><div class="field"><label>Reward points</label><input type="number" value="5"></div><div class="field"><label>Daily limit</label><input type="number" value="1"></div></div><button class="btn primary" style="margin-top:15px" onclick="closeModal();toast('Task saved')">Save Task</button>`)}
function openAdultMovie(){showModal(`<div class="modal-head"><h2>Add Adult Movie</h2><button class="btn" onclick="closeModal()">×</button></div><div class="field"><label>Title</label><input placeholder="Adult movie title"></div><div class="field" style="margin-top:12px"><label>Separate adult ad block</label><input placeholder="Ad block ID"></div><button class="btn primary" style="margin-top:15px" onclick="closeModal();toast('Adult movie saved in demo')">Save Adult Movie</button>`)}
function showModal(body){$("#modal").innerHTML=`<div class="modal-box">${body}</div>`;$("#modal").classList.remove("hidden")}
function closeModal(){$("#modal").classList.add("hidden")}
render();
