const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const defaults={appName:"Cine Hub4",botUsername:"@Cinehub4bot",telegramBotLink:"https://t.me/Cinehub4bot",telegramChannelLink:"",howToEarnVideo:"",unlockCost:5,unlockHours:15,adReward:2,dailyAdLimit:20,categories:["All","Bangla","Hollywood","Bollywood","Series","Trending"],adBlocks:{rewarded:"43222",interstitial:"",banner:"",task:"",adult:""}};
let cfg={...defaults,...JSON.parse(localStorage.getItem("cinehub4_settings")||"{}")};
let movies=JSON.parse(localStorage.getItem("cinehub4_movies")||"null")||[
{id:1,title:"PRINCE",year:2026,rating:8.7,genre:"Action • Drama",category:"Bangla",clicks:1842,downloads:921,poster:""},
{id:2,title:"ROCKSTAR",year:2026,rating:8.1,genre:"Drama • Romance",category:"Bollywood",clicks:1421,downloads:702,poster:""},
{id:3,title:"SPIDER-MAN: Brand New Day",year:2026,rating:8.5,genre:"Action • Adventure",category:"Hollywood",clicks:1207,downloads:641,poster:""}];
const state={page:localStorage.getItem("cinehub4_page")||"home",adultOK:false,points:Number(localStorage.getItem("cinehub4_points")||12),query:"",category:"All",history:JSON.parse(sessionStorage.getItem("cinehub4_history")||"[]")};
function save(){localStorage.setItem("cinehub4_movies",JSON.stringify(movies));localStorage.setItem("cinehub4_points",state.points)}
function toast(t){const x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1600)}
function nav(p,opts={}){if(p===state.page&&!opts.force)return;if(!opts.fromBack){state.history.push(state.page);if(state.history.length>30)state.history.shift();sessionStorage.setItem("cinehub4_history",JSON.stringify(state.history));}state.page=p;localStorage.setItem("cinehub4_page",p);try{window.Telegram?.WebApp?.HapticFeedback?.selectionChanged()}catch(e){}render(true);window.scrollTo({top:0,behavior:"smooth"})}
function goBack(){const prev=state.history.pop();sessionStorage.setItem("cinehub4_history",JSON.stringify(state.history));if(prev){state.page=prev;localStorage.setItem("cinehub4_page",prev);render(true)}else{state.page="home";localStorage.setItem("cinehub4_page","home");render(true)}window.scrollTo({top:0,behavior:"smooth"})}
function poster(m){return m.poster?`<img class="poster-img" src="${m.poster}" alt="">`:`<div class="poster"><div class="poster-title">${m.title}</div><span>🎬 CINE HUB4</span></div>`}
function card(m){return `<article class="movie-card" onclick="detail(${m.id})">${poster(m)}<div class="movie-meta"><div class="movie-title">${m.title}</div><div class="muted">${m.year} • ⭐ ${m.rating} • ${m.genre}</div><div class="chips"><span class="chip">HD</span><span class="chip">${m.category||"Movie"}</span></div></div></article>`}
function home(){const cats=cfg.categories||defaults.categories;const recent=movies.slice().sort((a,b)=>b.id-a.id).slice(0,10);const trending=movies.slice().sort((a,b)=>(b.clicks+b.downloads)-(a.clicks+a.downloads)).slice(0,10);return `<div class="welcome"><div><small>WELCOME TO</small><h1>${cfg.appName}</h1><p>Premium movie library • fast access • smart unlock</p></div><div class="coin">🪙 ${state.points}</div></div><div class="searchbox"><input id="q" placeholder="মুভির নাম লিখে সার্চ করুন..." value="${state.query}"><button class="primary" onclick="doSearch()">⌕</button></div><div class="category-row">${cats.map(c=>`<button class="pill ${state.category===c?"active":""}" onclick="filterCat('${c.replace(/'/g,"\\'")}')">${c}</button>`).join("")}</div><div class="adbox">Advertisement</div><div class="section-title"><b>🆕 Recently Added</b><span>সব দেখুন</span></div>${recent.map(card).join("")}<div class="section-title"><b>🔥 Trending</b><span>Most clicked & downloaded</span></div>${trending.map(card).join("")}`}
function moviesPage(){const list=state.category==="All"?movies:movies.filter(m=>(m.category||"").toLowerCase()===state.category.toLowerCase());return `<div class="section-title"><b>🎬 Movie Library</b><span>${list.length} titles</span></div>${list.map(card).join("")||`<div class="panel">কোনো মুভি পাওয়া যায়নি।</div>`}`}
function series(){return `<div class="section-title"><b>Series</b><span>Complete series</span></div>${movies.filter(m=>m.category==="Series").map(card).join("")||`<div class="panel">Series যোগ করা হয়নি।</div>`}`}
function adult(){if(!state.adultOK)return `<div class="adult-warning"><div class="adult-icon">18+</div><h2>Adult Access</h2><p class="muted">এই বিভাগে প্রাপ্তবয়স্ক কনটেন্ট রয়েছে। প্রবেশের আগে বয়স নিশ্চিত করুন।</p><button class="primary pink wide" onclick="confirmAdult()">আমি ১৮+</button><button class="pill wide" onclick="nav('home')">ফিরে যান</button></div>`;return `<div class="section-title"><b>🔞 Adult Library</b><span>18+</span></div><div class="adbox">Adult Advertisement</div>${movies.filter(m=>m.adult).map(card).join("")||`<div class="panel">Adult movies will appear here after admin adds them.</div>`}`}
function profile(){return `<div class="profile-card"><div class="row"><div class="avatar">S</div><div><div class="profile-name">Telegram User <span class="verified">✓ Verified</span></div><div class="muted">@telegram_user</div></div></div><div class="stats"><div class="stat"><b>${state.points}</b><span>Points</span></div><div class="stat"><b>15h</b><span>Unlock</span></div><div class="stat"><b>0</b><span>Watched</span></div><div class="stat"><b>0</b><span>Referrals</span></div></div></div><div class="panel"><h3>Point Center</h3><div class="task"><span>🪙 My Points</span><b>${state.points}</b></div><div class="task"><span>📺 Daily Ad Earning</span><button class="primary" onclick="nav('points')">Earn</button></div><div class="task"><span>👥 Referral</span><button class="pill" onclick="shareRef()">Share</button></div><div class="task"><span>💳 Buy Points</span><button class="pill" onclick="nav('buy')">Buy</button></div></div>`}
function points(){return `<div class="section-title"><b>🪙 My Points</b><span>${state.points} points</span></div><div class="panel"><div class="amount">${state.points} <span class="muted">points</span></div><div class="task"><span>📺 Watch Ad & Earn</span><b>+${cfg.adReward}</b><button class="primary cyan" onclick="watchAd('rewarded')">Watch</button></div><div class="task"><span>🛒 Buy Points</span><button class="primary pink" onclick="nav('buy')">Buy</button></div><div class="task"><span>👥 Refer & Earn</span><button class="pill" onclick="shareRef()">Share</button></div></div><div class="panel"><h3>Daily Ad Limit</h3><div class="task"><span>Only for earning points</span><b>${cfg.dailyAdLimit}/day</b></div><div class="muted">Movie unlock-এর সময় ad limit প্রযোজ্য নয়।</div></div>`}
function tasks(){return `<div class="section-title"><b>✓ Daily Tasks</b><span>Earn points</span></div><div class="panel"><div class="task"><span>📺 Watch rewarded ad</span><button class="primary" onclick="watchAd('task')">+${cfg.adReward}</button></div><div class="task"><span>📣 Join Telegram</span><button class="pill" onclick="openLink(cfg.telegramChannelLink)">Join</button></div><div class="task"><span>👥 Refer a friend</span><button class="pill" onclick="shareRef()">Share</button></div><div class="task"><span>🎥 How to earn points</span><button class="pill" onclick="howToEarn()">Watch</button></div></div>`}
function settings(){return `<div class="section-title"><b>⚙ Settings</b></div><div class="panel"><div class="task"><span>Language</span><select class="pill" style="appearance:auto" onchange="CINEHUB4_LANG.set(this.value)"><option value="en" ${CINEHUB4_LANG.get()==="en"?"selected":""}>English</option><option value="bn" ${CINEHUB4_LANG.get()==="bn"?"selected":""}>বাংলা</option></select></div><div class="task"><span>Telegram</span><button class="pill" onclick="openLink(cfg.telegramBotLink)">Open</button></div><div class="task"><span>How To Earn</span><button class="pill" onclick="howToEarn()">Watch Video</button></div></div>`}
function buy(){return `<div class="section-title"><b>💳 Buy Points</b></div><div class="panel"><div class="task"><span>110 Points</span><b>৳99</b></div><div class="task"><span>500 Points</span><b>৳399</b></div><div class="task"><span>1200 Points</span><b>৳899</b></div><button class="primary pink wide" onclick="toast('Payment request form opened')">Submit Payment Proof</button></div>`}
function detail(id){const m=movies.find(x=>x.id===id);if(!m)return; m.clicks=(m.clicks||0)+1;save();const cost=Number(cfg.unlockCost)||5;$("#screen").innerHTML=`<div class="movie-card">${poster(m)}<div class="movie-meta"><h2>${m.title}</h2><div class="muted">${m.year} • ⭐ ${m.rating} • ${m.genre}</div><p class="muted">Premium movie content. Unlock with points or watch the rewarded ad.</p></div></div><div class="unlock"><div class="section-title"><b>Unlock</b><span>${state.points} points</span></div><div class="stats"><div class="stat"><b>${cost}</b><span>Cost</span></div><div class="stat"><b>${cfg.unlockHours}h</b><span>Access</span></div><div class="stat"><b>∞</b><span>Movies while active</span></div><div class="stat"><b>AD</b><span>Alternative</span></div></div><button class="primary cyan wide" onclick="unlockPoints()">🪙 Use My Points</button><button class="primary pink wide" onclick="watchAd('unlock')">▶ Watch Ad to Unlock</button></div>`}
function unlockPoints(){const c=Number(cfg.unlockCost)||5;if(state.points<c){toast('পয়েন্ট যথেষ্ট নেই');return}state.points-=c;save();toast(`Unlocked for ${cfg.unlockHours} hours`);}
function watchAd(mode){const id=mode==='adult'?cfg.adBlocks.adult:cfg.adBlocks.rewarded;if(!id){toast('Admin has not configured this Ad Block ID');return}const m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modal-card"><div class="video-ad"><div><div class="play">▶</div><b>Ad Block #${id}</b><div class="muted">Demo rewarded advertisement</div></div></div><button class="primary cyan wide" id="completeDemoAd">Complete Demo Ad</button></div>`;document.body.appendChild(m);$('#completeDemoAd').onclick=()=>{m.remove();if(mode==='unlock'){toast('Movie unlocked for '+cfg.unlockHours+' hours')}else{state.points+=Number(cfg.adReward||0);save();toast('+'+cfg.adReward+' points earned');render()}}}
function doSearch(){state.query=$("#q")?.value.trim()||"";toast(state.query?`Searching: ${state.query}`:'মুভির নাম লিখুন')}
function filterCat(c){state.category=c;nav('movies')}
function confirmAdult(){state.adultOK=true;render()}
function shareRef(){toast('Referral link copied')}
function openLink(url){if(url)location.href=url;else toast('Admin has not configured this link yet')}
function getTelegramUserId(){
  try{return window.Telegram?.WebApp?.initDataUnsafe?.user?.id?String(window.Telegram.WebApp.initDataUnsafe.user.id):''}catch(e){return ''}
}
function isCineHubAdmin(){
  const id=getTelegramUserId();
  const admins=(window.APP_CONFIG?.adminIds||[window.APP_CONFIG?.adminDemoId]).map(String);
  return !!id && admins.includes(id);
}
function setupAdminButton(){
  const b=document.getElementById('adminPanelBtn');
  if(!b)return;
  if(isCineHubAdmin()){
    b.classList.remove('hidden');
    b.onclick=()=>{try{window.Telegram?.WebApp?.HapticFeedback?.impactOccurred('light')}catch(e){};location.href='admin.html'};
  }else b.classList.add('hidden');
}
function howToEarn(){if(cfg.howToEarnVideo)location.href=cfg.howToEarnVideo;else toast('Admin has not added the How To Earn video yet')}
function render(animate=false){const views={home,movies:moviesPage,series,adult,profile,points,tasks,settings,buy};const screen=$("#screen");screen.innerHTML=views[state.page]?views[state.page]():home();if(animate){screen.classList.remove("page-enter");void screen.offsetWidth;screen.classList.add("page-enter")}$$('.nav-item').forEach(b=>b.classList.toggle("active",b.dataset.page===state.page));window.CINEHUB4_LANG?.translateDOM()}
try{window.Telegram?.WebApp?.ready();window.Telegram?.WebApp?.expand()}catch(e){}
$("#menuBtn").onclick=()=>$("#drawer").classList.remove('hidden');$("#closeDrawer").onclick=()=>$("#drawer").classList.add('hidden');$(".drawer-backdrop").onclick=()=>$("#drawer").classList.add('hidden');$$('.drawer button[data-page]').forEach(b=>b.onclick=()=>{$('#drawer').classList.add('hidden');nav(b.dataset.page)});$$('.nav-item').forEach(b=>b.onclick=()=>nav(b.dataset.page));$("#backBtn").onclick=()=>goBack();setupAdminButton();render(false);setTimeout(()=>document.getElementById("appSplash")?.remove(),1900);
